Repository googleapis/java-managed-identities, pull requests merged in 2021-09, with the labels that each got.

#102 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#114 chore(java): install maven 3.8.1 at runtime
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  renovate.json
  synth.metadata
Labels: cla: yes, context: full

#122 chore: update owlbot java image
  .github/.OwlBot.lock.yaml
Labels: automerge, cla: yes

#118 chore: relocate owl bot post processor
  .github/.OwlBot.yaml
Labels: automerge, cla: yes

#128 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes
