Repository googleapis/java-managed-identities, pull requests merged in 2021-05, with the labels that each got.

#35 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: automerge, cla: yes

#36 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: automerge, cla: yes, context: none

#39 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#41 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#42 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#44 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#46 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#51 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
